#List methods= sort,sort(reverse=True),reverse,append,insert,remove,pop
List=[1,2,3,4,5]
print("Orignal List",List)
List.append(6)
print("Appended List is :",List)
List.sort(reverse=True)
print("Descending order List :",List)
List.sort()
print("Accending order List :",List)
List.remove(List[0])
print("Removed 0th index value :",List)
#inserts at particular number List.insert(indx,num)
List.insert(0,1)
print("Again Inserted 0th value :",List)
List.insert(2,8)
print("Inserted indx 2,8 :",List)
List.remove(8)
print("We can directly remove the particular num :",List)
List.pop(2)
print("Pop method removes the particular indx number :",List)